// PalaLab racquet catalog - SERVER endpoint (Vercel Edge Function).
// Serves the curated database instead of bundling it into the browser,
// so the curated-data moat cannot be scraped from page source.
export const config = { runtime: "edge" };
const MARKET_RACQUETS = [
  // ── OXDOG (added Jul 2026) — a full spectrum of the range, not just the hero
  //    frame: round (Sense Pro), teardrop (Pure Tour X) and four diamonds from
  //    the ultra-thin Pro Smash down to the light NXT-GEN, control Tour X and
  //    the best-selling Ultimate Pro. Specs cross-checked across OXDOG's own
  //    launch pages plus PadelVerdict / Padelful / padel.how / PadelReference.
  {
    id: "oxdog-ultimate-pro-smash-2025",
    brand: "Oxdog",
    model: "Ultimate Pro Smash (2025)",
    shapeId: "diamond",
    coreId: "eva-medium",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 66,
    weightG: 367,
    balanceCm: 26.8,
    thicknessMm: 30,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "The hero 'breaks-the-mold' frame: an ultra-thin 30mm diamond (pros usually run 38mm). Renewed high-density HES-Carbon face, firm medium+ EVA, oversized front/side air ports and Double-Size Holes with PowerRibs — OXDOG claims up to 15% higher head speed in the air. Reviews: extremely fast and stable overhead, feels lighter than its ~365-370g, but stiff and demanding with reduced feedback on touch/defensive shots (the 'no feel' reputation). Weight cited 365-370g; core medium+/medium-hard across sources.",
  },
  {
    id: "oxdog-ultimate-pro",
    brand: "Oxdog",
    model: "Ultimate Pro",
    shapeId: "diamond",
    coreId: "eva-medium",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 62,
    weightG: 365,
    balanceCm: 26.8,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "OXDOG's flagship best-seller. Standard-thickness power diamond, head-heavy, medium-hard EVA, HES-Carbon face, sandy surface. Reviewers praise it for combining real smash power with better feel and maneuverability than the more demanding Pro+.",
  },
  {
    id: "oxdog-ultimate-tour-x",
    brand: "Oxdog",
    model: "Ultimate Tour X",
    shapeId: "diamond",
    coreId: "eva-medium",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 60,
    weightG: 355,
    balanceCm: 26.0,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "mid",
    sourceConfidence: "medium",
    note: "The lightest, most control-oriented diamond in the Ultimate line — medium balance and lower weight give it noticeably more maneuverability and forgiveness than the Pro/Smash at the cost of raw power. HES-Carbon, sandy surface for spin. A 'diamond with some defense'.",
  },
  {
    id: "oxdog-ultimate-nxt-gen",
    brand: "Oxdog",
    model: "Ultimate NXT-GEN",
    shapeId: "diamond",
    coreId: "eva-soft",
    faceId: "carbon-3k",
    frameId: "hybrid-frame",
    surfaceId: "rough",
    textureLevel: 58,
    weightG: 345,
    balanceCm: 26.0,
    thicknessMm: 35,
    level: "intermediate",
    priceTier: "mid",
    sourceConfidence: "medium",
    note: "The accessible 'gateway diamond': a lighter 35mm frame with a soft EVA core and an 8K-carbon-plus-fiberglass face for forgiveness. Aimed at casual/intermediate players, juniors and smaller hands — easy power without a big swing, more comfort than the stiffer Ultimate diamonds.",
  },
  {
    id: "oxdog-sense-pro",
    brand: "Oxdog",
    model: "Sense Pro",
    shapeId: "round",
    coreId: "eva-medium",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 60,
    weightG: 365,
    balanceCm: 25.0,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "mid",
    sourceConfidence: "medium",
    note: "OXDOG's marquee round control frame, marketed as one of the fastest round rackets made. Medium+ EVA, HES-Carbon, sandy surface, forgiving round sweet spot with surprising head speed for the shape. Balance cited medium (spec sheets) to head-heavy (marketing).",
  },
  {
    id: "oxdog-pure-tour-x",
    brand: "Oxdog",
    model: "Pure Tour X",
    shapeId: "teardrop",
    coreId: "eva-medium",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "smooth",
    textureLevel: 15,
    weightG: 365,
    balanceCm: 26.0,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "mid",
    sourceConfidence: "medium",
    note: "The control/all-court option (the 'Pure' line that replaced 'Sense' for 2025+): a hybrid teardrop with a medium EVA core, 8K HES-Carbon, and — unlike the sandy Ultimate line — a matte/smooth face. Large sweet spot, strong maneuverability and very predictable off-centre behaviour; a defender-friendly all-courter (~58 RA, 260mm balance).",
  },
  {
    id: "babolat-technical-viper-3",
    brand: "Babolat",
    model: "Technical Viper 3.0 (2026)",
    shapeId: "diamond",
    coreId: "eva-hard",
    faceId: "carbon-3k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 78,
    weightG: 370,
    balanceCm: 26.5,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "Babolat's flagship power frame. Hard EVA core, 3K carbon face, diamond shape — converges across brand site, multiple retailers, and independent reviews on weight (370g ±10) and a high/head-heavy balance.",
  },
  {
    id: "babolat-technical-viper-soft-3",
    brand: "Babolat",
    model: "Technical Viper Soft 3.0 (2026)",
    shapeId: "diamond",
    coreId: "eva-medium",
    faceId: "carbon-3k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 62,
    weightG: 370,
    balanceCm: 26.3,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "Same diamond shape and weight as the standard Technical Viper, but a softer EVA core and Soft Carbon face for more flex and comfort at a similar power ceiling.",
  },
  {
    id: "bullpadel-vertex-05",
    brand: "Bullpadel",
    model: "Vertex 05 (2026)",
    shapeId: "diamond",
    coreId: "eva-medium",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 70,
    weightG: 370,
    balanceCm: 25.4,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "Bullpadel's flagship. MultiEVA dual-density core and 12K carbon face. Sources agree on a diamond shape with a triangulated double-diagonal bridge for stability, though balance figures vary by 1-2cm across listings — used the most-repeated figure.",
  },
  {
    id: "bullpadel-vertex-05-hybrid",
    brand: "Bullpadel",
    model: "Vertex 05 Hybrid (2026)",
    shapeId: "teardrop",
    coreId: "eva-medium",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 70,
    weightG: 370,
    balanceCm: 25.0,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "approximate",
    note: "Shares the Vertex Core bridge tech with the diamond model but in a hybrid/teardrop mould with a lower balance. One source mislabeled this as round shape, contradicting every other source's hybrid/teardrop description — treated as an outlier and excluded.",
  },
  {
    id: "nox-at10-genius-12k",
    brand: "Nox",
    model: "AT10 Genius 12K Alum Xtrem (2026)",
    shapeId: "round",
    coreId: "eva-hard",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 85,
    weightG: 368,
    balanceCm: 25.5,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "Agustín Tapia's signature. Round shape per Nox's own product page — note this differs from the 18K Genius variant below, which Nox itself lists as teardrop/hybrid. HR3 Black EVA core, weight range 360-375g.",
  },
  {
    id: "nox-at10-genius-18k",
    brand: "Nox",
    model: "AT10 Genius 18K Alum (2026)",
    shapeId: "teardrop",
    coreId: "eva-medium",
    faceId: "carbon-18k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 85,
    weightG: 368,
    balanceCm: 25.5,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "approximate",
    note: "Softer, more comfortable sibling to the 12K version above, with a teardrop/hybrid shape per Nox's own listing. Multi-layer MLD Black EVA core.",
  },
  {
    id: "nox-at10-genius-attack-18k",
    brand: "Nox",
    model: "AT10 Genius Attack 18K Alum (2026)",
    shapeId: "diamond",
    coreId: "eva-hard",
    faceId: "carbon-18k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 85,
    weightG: 368,
    balanceCm: 26.4,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "The diamond, high-balance \"Attack\" variant of the AT10 Genius line, built for finishers rather than point-builders.",
  },
  {
    id: "nox-ml10-pro-cup",
    brand: "Nox",
    model: "ML10 Pro Cup / Ventus Control (2026)",
    shapeId: "round",
    coreId: "eva-medium",
    faceId: "carbon-3k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 62,
    weightG: 367,
    balanceCm: 24.5,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "mid",
    sourceConfidence: "high",
    note: "Miguel Lamperti's long-running control signature. Round shape, low/head-light balance, large sweet spot — consistently described across many sources as a benchmark control racquet.",
  },
  {
    id: "nox-x-hero",
    brand: "Nox",
    model: "X-Hero (2026)",
    shapeId: "round",
    coreId: "eva-soft",
    faceId: "fiberglass",
    frameId: "fiberglass-frame",
    surfaceId: "smooth",
    textureLevel: 15,
    weightG: 355,
    balanceCm: 24.0,
    thicknessMm: 38,
    level: "beginner",
    priceTier: "budget",
    sourceConfidence: "high",
    note: "Entry-level round racquet aimed at beginner-to-improving players. Fiberglass face, soft EVA core, large sweet spot — designed to make learning technique easier rather than to compete on power.",
  },
  {
    id: "adidas-metalbone-2026",
    brand: "Adidas",
    model: "Metalbone (2026)",
    shapeId: "diamond",
    coreId: "eva-soft",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 55,
    weightG: 353,
    balanceCm: 26.5,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "approximate",
    note: "Alejandro Galán's signature. Diamond shape, head-heavy, Soft Performance EVA core. Weight is genuinely disputed across sources (declared base 345-360g on some listings, 353g manufacturer figure elsewhere) — has an adjustable weight system that can add up to ~11g, which likely explains some of the spread.",
  },
  {
    id: "adidas-metalbone-ctrl",
    brand: "Adidas",
    model: "Metalbone Carbon CTRL (2026)",
    shapeId: "round",
    coreId: "eva-soft",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 65,
    weightG: 365,
    balanceCm: 24.5,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "The round, control-oriented counterpart within the Metalbone family — same frame tech (Octagonal Structure, Power Groove) but even balance instead of head-heavy.",
  },
  {
    id: "head-extreme-pro-2026",
    brand: "Head",
    model: "Extreme Pro (2026)",
    shapeId: "diamond",
    coreId: "eva-hard",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 70,
    weightG: 370,
    balanceCm: 27.0,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "Diamond shape, high/head-heavy balance (~270mm), Power Foam core. Strongly convergent across many independent sources as a firm, attack-first frame for advanced players.",
  },
  {
    id: "starvie-raptor-plus",
    brand: "StarVie",
    model: "Raptor + (2026)",
    shapeId: "teardrop",
    coreId: "eva-medium",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 65,
    weightG: 367,
    balanceCm: 25.5,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "mid",
    sourceConfidence: "high",
    note: "Teardrop all-rounder. M-Eva Balance medium-density core, 3D carbon face, adjustable Dynamic Star weight system (small ±0.3-0.6cm balance range, not a major spec driver on its own).",
  },
  {
    id: "wilson-bela-lt",
    brand: "Wilson",
    model: "Bela LT (V2.5/V3)",
    shapeId: "teardrop",
    coreId: "eva-soft",
    faceId: "carbon-3k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 55,
    weightG: 358,
    balanceCm: 26.0,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "mid",
    sourceConfidence: "high",
    note: "The lightest racquet in Wilson's Bela (Belasteguín) line — teardrop shape, soft EVA core, strongly convergent across independent reviews and retailers as a comfort-first, arm-friendly racquet that still keeps real spin and smash capability. Fills a genuine gap versus the more aggressive Bela Pro/V3 below.",
  },
  {
    id: "wilson-bela-pro",
    brand: "Wilson",
    model: "Bela Pro / V3",
    shapeId: "diamond",
    coreId: "eva-hard",
    faceId: "carbon-3k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 65,
    weightG: 365,
    balanceCm: 26.0,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "approximate",
    note: "Wilson's flagship power signature. Sources place it anywhere from diamond to hybrid shape depending on the specific V2.5/V3/Pro variant — used the most-repeated diamond/high-balance description, but treat this one as a family representative rather than one exact SKU.",
  },
  {
    id: "siux-electra-pro",
    brand: "Siux",
    model: "Electra Pro (2026)",
    shapeId: "teardrop",
    coreId: "eva-hard",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 62,
    weightG: 362,
    balanceCm: 25.5,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "mid",
    sourceConfidence: "high",
    note: "Franco Stupaczuk's signature. Teardrop shape, hard EVA core, 12K carbon — strongly convergent across independent reviews as a firm, direct racquet whose control score genuinely outscores its power score, an unusual combination for a hard-core build.",
  },
  {
    id: "head-graphene-alpha-power",
    brand: "Head",
    model: "Graphene 360 Alpha Power 2.0",
    shapeId: "diamond",
    coreId: "eva-hard",
    faceId: "graphene",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 62,
    weightG: 368,
    balanceCm: 26.5,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "mid",
    sourceConfidence: "approximate",
    note: "The one genuinely graphene-faced model in this set — Head builds Graphene 360 into the frame/structure for torsion and rigidity rather than as a separate face layer, which matters if you're comparing this tool's 'graphene' face-material option directly: real-world graphene use in padel is closer to a frame-reinforcement technique than a distinct visible face material.",
  },
  // ---- Bullpadel Hack 04 line -----------------------------------------------
  {
    id: "bullpadel-hack-04-2026",
    brand: "Bullpadel",
    model: "Hack 04 (2026)",
    shapeId: "diamond",
    coreId: "hybrid-core",
    faceId: "carbon-18k",
    frameId: "carbon-frame",
    surfaceId: "3d-print",
    textureLevel: 90,
    weightG: 370,
    balanceCm: 26.4,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "Paquito Navarro's signature weapon. TriCarbon 18K face (three-directional carbon weave unique to Bullpadel), multi-density MultiEva core, and the CustomWeight system allowing up to +22g and ±1cm balance adjustment. Diamond with concentric-circle hole pattern redesigned for 2026 to enlarge the sweet spot. Positioned at the extreme power-speed end of the Bullpadel lineup.",
  },
  {
    id: "bullpadel-hack-04-hybrid-2026",
    brand: "Bullpadel",
    model: "Hack 04 Hybrid (2026)",
    shapeId: "teardrop",
    coreId: "hybrid-core",
    faceId: "carbon-18k",
    frameId: "carbon-frame",
    surfaceId: "3d-print",
    textureLevel: 90,
    weightG: 368,
    balanceCm: 25.5,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "Teardrop version of the Hack 04 line — combines Hack power character with more accessible balance. Aluminized 18K carbon face, triple-bridge design, same CustomWeight system as the diamond version. Reviewers describe it as 'control-leaning all-court with enough punch to finish' — the rational Hack choice for players who transition between net and baseline.",
  },
  // ---- Bullpadel Neuron 02 line ---------------------------------------------
  {
    id: "bullpadel-neuron-02-2026",
    brand: "Bullpadel",
    model: "Neuron 02 (2026)",
    shapeId: "teardrop",
    coreId: "hybrid-core",
    faceId: "carbon-3k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 65,
    weightG: 370,
    balanceCm: 25.5,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "Fede Chingotto's control-first teardrop. Even balance (~25.5cm) for smooth preparation and placement-first timing. PrismLock triangulated frame resists torsion. Neuron Core inverted pentagonal bridge channels energy for firm, precise contact. Multi-density MultiEva core. Ease Vibe dampeners absorb up to 49% vibration. Surgical control over raw power.",
  },
  {
    id: "bullpadel-neuron-02-edge-2026",
    brand: "Bullpadel",
    model: "Neuron 02 Edge (2026)",
    shapeId: "diamond",
    coreId: "hybrid-core",
    faceId: "carbon-3k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 65,
    weightG: 370,
    balanceCm: 26.2,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "Diamond sibling to the Neuron 02 — same PrismLock/MultiEva/X-Tend Carbon 3K spec but a higher balance for more overhead aggression. Control-first philosophy applied to a diamond mold: larger sweet spot than typical diamond, composed under pressure, not a pure smash weapon. For advanced players who want to dictate rallies with precision from an attacking position.",
  },
  // ---- Adidas Metalbone HRD+ -----------------------------------------------
  {
    id: "adidas-metalbone-hrd-2026",
    brand: "Adidas",
    model: "Metalbone HRD+ (2026)",
    shapeId: "diamond",
    coreId: "eva-hard",
    faceId: "carbon-18k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 60,
    weightG: 356,
    balanceCm: 27.0,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "Ale Galán's pro weapon — the hardest-hitting Metalbone in the 2026 lineup. Carbon Aluminized 16K face, High Memory EVA core (high-density, fast rebound on hard swings), Octagonal Structure, Extra Power Grip (+15mm handle for inertia and power). Weight & Balance System adjustable ±11.2g. Balance at 278mm — deep head-heavy territory. Very narrow operating window, extreme upside for technically clean elite players.",
  },
  // ---- Head Coello Pro 2026 ------------------------------------------------
  {
    id: "head-coello-pro-2026",
    brand: "Head",
    model: "Coello Pro (2026)",
    shapeId: "diamond",
    coreId: "eva-hard",
    faceId: "carbon-3k",
    frameId: "auxetic-frame",
    surfaceId: "rough",
    textureLevel: 70,
    weightG: 370,
    balanceCm: 27.2,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "Arturo Coello's signature weapon — the most aggressive offensive racket in Head's 2026 lineup. Auxetic 2.0 frame (widens on impact rather than compressing, channeling energy into the ball rather than absorbing it). Carbon Hybrid face (carbon + fiberglass weave), Power Foam core for explosive rebound. Balance at 272mm. RA ~72 — high stiffness. Not for players who rely on forgiveness; rewards clean technique and aggressive forward positioning absolutely.",
  },
  {
    id: "head-coello-motion-2026",
    brand: "Head",
    model: "Coello Motion (2026)",
    shapeId: "diamond",
    coreId: "eva-medium",
    faceId: "carbon-3k",
    frameId: "auxetic-frame",
    surfaceId: "rough",
    textureLevel: 70,
    weightG: 355,
    balanceCm: 26.5,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "mid",
    sourceConfidence: "high",
    note: "The accessible version of the Coello range — same Auxetic 2.0 frame technology, diamond shape, but at 355g with a more moderate balance for better maneuverability. Designed for players who want Coello's offensive character without the full physical demands of the Pro. Same family, fundamentally different swing requirement.",
  },
  // ---- StarVie additions ---------------------------------------------------
  {
    id: "starvie-astrum-plus-2026",
    brand: "StarVie",
    model: "Astrum+ (2026)",
    shapeId: "teardrop",
    coreId: "eva-medium",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 60,
    weightG: 368,
    balanceCm: 25.8,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "StarVie's versatile flagship for 2026. Teardrop with medium balance — the all-court specialist positioned above the Raptor. 12K Carbon Hyper face with Spin Boost Tech, M-EVA Balance medium-density core. Air Booster aerodynamics for swing speed, Shock Shield vibration absorption, Z-Shock grip. Control 8.4, Maneuverability 8.6 per PadelVerdict. For advanced hybrid/all-court players who value versatility over raw power ceiling.",
  },
  {
    id: "starvie-triton-plus-2026",
    brand: "StarVie",
    model: "Triton+ (2026)",
    shapeId: "diamond",
    coreId: "eva-hard",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 65,
    weightG: 372,
    balanceCm: 26.6,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "approximate",
    note: "StarVie's power flagship above the Astrum+. Diamond shape, high balance, stiff construction — the attacker's choice in the StarVie lineup. Aluminized carbon face, hard core. For players who want more overhead firepower than the Astrum+ can deliver.",
  },
  // ---- Nox additions -------------------------------------------------------
  {
    id: "nox-equation-2026",
    brand: "Nox",
    model: "Equation Soft (2026)",
    shapeId: "teardrop",
    coreId: "eva-soft",
    faceId: "carbon-12k",
    frameId: "hybrid-frame",
    surfaceId: "rough",
    textureLevel: 55,
    weightG: 362,
    balanceCm: 25.5,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "mid",
    sourceConfidence: "high",
    note: "Comfort-driven control racket for intermediate players — a teardrop with soft EVA core positioned between the all-beginner ML10 and the advanced AT10 range. Good spin, high comfort, forgiving sweet spot. The 'soft' version of the Equation line means the face flexes more on contact for better arm protection. Ideal for players building consistency who want more face response than the ML10 but aren't ready for the AT10's demands.",
  },
  {
    id: "nox-x-zero-2026",
    brand: "Nox",
    model: "X-Zero (2026)",
    shapeId: "round",
    coreId: "eva-soft",
    faceId: "fiberglass",
    frameId: "hybrid-frame",
    surfaceId: "rough",
    textureLevel: 12,
    weightG: 358,
    balanceCm: 24.8,
    thicknessMm: 38,
    level: "beginner",
    priceTier: "budget",
    sourceConfidence: "high",
    note: "Nox's true entry-level racket — round, soft, light, and maximally forgiving. Fiberglass face, soft EVA core, low balance for maneuverability. HR3 rubber variant. Large sweet spot, easy ball exit. The step above the X-Hero for beginners who want the same accessibility with slightly more durability. Certified the most accessible Nox model in the 2026 lineup per multiple sources.",
  },
  // ---- Wilson additions ----------------------------------------------------
  {
    id: "wilson-blade-v3-2026",
    brand: "Wilson",
    model: "Blade V3 (2026)",
    shapeId: "teardrop",
    coreId: "eva-medium",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 55,
    weightG: 365,
    balanceCm: 26.0,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "The flagship Wilson padel racket — teardrop with medium balance, 12K carbon face, medium EVA core. Designed around control and spin rather than pure power. The Bela Pro's evolution — slightly more balanced and accessible than the Bela Pro/V3, less head-heavy than most comparable advanced teardrops. Best for all-court players who want attacking capability with controlled net play.",
  },
  {
    id: "wilson-blade-v3-ls-2026",
    brand: "Wilson",
    model: "Blade V3 LS (2026)",
    shapeId: "teardrop",
    coreId: "eva-soft",
    faceId: "carbon-12k",
    frameId: "hybrid-frame",
    surfaceId: "rough",
    textureLevel: 55,
    weightG: 350,
    balanceCm: 25.4,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "mid",
    sourceConfidence: "high",
    note: "Lightweight version of the Blade V3 — softer core, hybrid frame, notably lighter at ~350g. Designed for intermediate players who want Wilson's Blade character without the full arm demands of the V3. Reviewers consistently note the easier swing and lower fatigue over long sessions. A practical step-up from the Bela LT.",
  },
  // ---- Siux additions -------------------------------------------------------
  {
    id: "siux-diablo-2026",
    brand: "Siux",
    model: "Diablo (2026)",
    shapeId: "diamond",
    coreId: "eva-hard",
    faceId: "carbon-18k",
    frameId: "carbon-frame",
    surfaceId: "3d-print",
    textureLevel: 65,
    weightG: 372,
    balanceCm: 26.8,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "approximate",
    note: "Siux's premium attacking diamond — 18K carbon face, hard EVA, 3D-printed surface texture for maximum spin. High balance. The power-first option in the Siux lineup, positioned above the Electra Pro for players who want maximum overhead output and can handle the demanding balance.",
  },
  // ---- Babolat additions ---------------------------------------------------
  {
    id: "babolat-juan-lebron-2026",
    brand: "Babolat",
    model: "Juan Lebrón (2026)",
    shapeId: "diamond",
    coreId: "eva-hard",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 62,
    weightG: 368,
    balanceCm: 26.6,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "approximate",
    note: "Juan Lebrón's signature Babolat model — diamond shape, carbon frame, hard EVA core. Slightly different character from the Viper line: carbon-12K face gives a more flexible, feedback-rich response than the Viper's 3K at the same weight and balance. Positioned for aggressive all-court players who want more ball feel than a pure power diamond provides.",
  },
  // ---- Head Speed line -----------------------------------------------------
  {
    id: "head-speed-motion-2026",
    brand: "Head",
    model: "Speed Motion (2026)",
    shapeId: "teardrop",
    coreId: "eva-medium",
    faceId: "carbon-12k",
    frameId: "hybrid-frame",
    surfaceId: "rough",
    textureLevel: 62,
    weightG: 362,
    balanceCm: 25.8,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "mid",
    sourceConfidence: "high",
    note: "Head's intermediate all-rounder — teardrop with medium balance, 12K carbon face, medium EVA core. Auxetic 2.0 technology (frame widens on impact) applied to a more accessible package than the Coello Pro. Reviewers consistently position it above the Extreme Pro for attacking potential while remaining accessible. The reference intermediate teardrop option in Head's 2026 range.",
  },
  // ---- Royal Padel -------------------------------------------------------
  {
    id: "royal-padel-m27-poly-2026",
    brand: "Royal Padel",
    model: "M27 Poly (2026)",
    shapeId: "round",
    coreId: "foam-pe",
    faceId: "carbon-3k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 75,
    weightG: 368,
    balanceCm: 25.2,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "mid",
    sourceConfidence: "high",
    note: "Royal Padel's flagship control round — polyethylene (PE) core rather than standard EVA gives it a distinctly softer, more cushioned impact feel. 3K carbon face, carbon frame. Medium-low balance for fast reactions and arm-friendly long sessions. Known for exceptional vibration absorption — the go-to recommendation for players with elbow sensitivity who still want an advanced-level racket. Control and defensive consistency over power.",
  },
  {
    id: "royal-padel-fury-2026",
    brand: "Royal Padel",
    model: "Fury (2026)",
    shapeId: "diamond",
    coreId: "eva-medium",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 75,
    weightG: 370,
    balanceCm: 26.0,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "mid",
    sourceConfidence: "high",
    note: "Royal Padel's attacking diamond — 12K rough carbon, mid-hard EVA core with Shock Absorption System. Even balance (260mm) rather than extreme head-heavy, which makes it more manageable than comparable diamonds while retaining power ceiling. PadelVerdict scores: Power 8.2, Spin 8.0, Stability 8.0. For advanced net-forward players who want overhead power with more forgiveness than a full head-heavy diamond.",
  },
  // ---- Siux extra model --------------------------------------------------
  {
    id: "siux-pegasus-2026",
    brand: "Siux",
    model: "Pegasus Control (2026)",
    shapeId: "round",
    coreId: "eva-soft",
    faceId: "carbon-12k",
    frameId: "hybrid-frame",
    surfaceId: "rough",
    textureLevel: 75,
    weightG: 360,
    balanceCm: 25.0,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "mid",
    sourceConfidence: "approximate",
    note: "Siux's control-oriented round — sits below the Electra Pro in the lineup, targeting intermediate players who want carbon face performance at a more accessible balance and weight. Soft EVA core, hybrid frame. Good spin potential from the 12K face with round shape's forgiving sweet spot.",
  },
  // ---- Black Crown -------------------------------------------------------
  {
    id: "black-crown-piton-2026",
    brand: "Black Crown",
    model: "Piton (2026)",
    shapeId: "diamond",
    coreId: "eva-hard",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 65,
    weightG: 370,
    balanceCm: 26.5,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "mid",
    sourceConfidence: "approximate",
    note: "Black Crown's flagship attacking diamond — high balance, hard EVA, 12K carbon. The brand's strongest power-oriented offering. Known for solid build quality and good value at the premium-mid price point compared to pro-brand equivalents. For advanced players seeking diamond power without the premium brand markup.",
  },
  {
    id: "black-crown-hack-2026",
    brand: "Black Crown",
    model: "Hack Control (2026)",
    shapeId: "round",
    coreId: "eva-medium",
    faceId: "carbon-3k",
    frameId: "hybrid-frame",
    surfaceId: "rough",
    textureLevel: 62,
    weightG: 362,
    balanceCm: 25.3,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "mid",
    sourceConfidence: "approximate",
    note: "Black Crown's control round for intermediate-advanced players. Medium EVA, 3K carbon face, hybrid frame. One of the more popular Black Crown options at club level — forgiving sweet spot, accessible balance, good feel for players developing consistency from the back court.",
  },
  // ---- Varlion -----------------------------------------------------------
  {
    id: "varlion-summum-carbon-2026",
    brand: "Varlion",
    model: "Summum Carbon (2026)",
    shapeId: "teardrop",
    coreId: "eva-medium",
    faceId: "carbon-18k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 75,
    weightG: 368,
    balanceCm: 26.0,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "approximate",
    note: "Varlion's flagship teardrop — Spanish brand known for temperature-adapted layups and high-grade construction. 18K carbon face for responsive feel, medium EVA, carbon frame. Positioned as a precision all-court racket for advanced players who want pro-level feel and durability without mainstream brand pricing.",
  },
  {
    id: "varlion-bourne-cube-2026",
    brand: "Varlion",
    model: "Bourne Cube ElbowCare (2026)",
    shapeId: "diamond",
    coreId: "eva-medium",
    faceId: "carbon-12k",
    frameId: "hybrid-frame",
    surfaceId: "rough",
    textureLevel: 75,
    weightG: 365,
    balanceCm: 26.3,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "approximate",
    note: "Varlion's premium attacking diamond with ElbowCare technology — vibration damping integrated into the frame to reduce arm impact despite the diamond's high balance. A practical answer to the common problem of wanting diamond power with arm protection. Hybrid frame absorbs vibration that a full carbon equivalent would transmit. Recommended by multiple sources for advanced players with shoulder or elbow sensitivity.",
  },
  // ---- Nox AT10 Pro Cup line ---------------------------------------------
  {
    id: "nox-at10-pro-cup-soft-2026",
    brand: "Nox",
    model: "AT10 Pro Cup Soft (2026)",
    shapeId: "teardrop",
    coreId: "eva-soft",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 62,
    weightG: 365,
    balanceCm: 25.8,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    note: "Advanced-level soft-feeling teardrop in the AT10 range — same mold as the AT10 Genius line but with a softer EVA core for players who want the Tapia-range frame character with more comfort and less arm strain. Precision, spin and feel over raw power. For advanced players who spend long sessions and prioritize touch and consistency over maximum smash output.",
  },
  // ── Brand-diversity expansion (2023–2026): 30 verified models across 17
  // brands (8 of them new to the DB). Each model's shape/weight/core-type/
  // face-type is confirmed by 3+ independent sources (see sourceCount);
  // exact balance-cm is derived from the agreed qualitative balance where a
  // brand doesn't publish a number. No Nox — added purely to broaden the
  // pool so recommendations aren't skewed by any one brand's model count.
  {
    id: "head-gravity-pro-2024",
    brand: "Head",
    model: "Gravity Pro 2024",
    shapeId: "round",
    coreId: "eva-medium",
    faceId: "carbon-3k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 60,
    weightG: 367,
    balanceCm: 26.0,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    sourceCount: 4,
    note: "Head's flagship round control racket; brand + padel.fyi + Tennis-Warehouse + padelreference confirm round shape, ~365-370g, medium core and woven carbon spin face; exact balance cm derived from the consistent head-light rating.",
  },
  {
    id: "head-gravity-motion-2024",
    brand: "Head",
    model: "Gravity Motion 2024",
    shapeId: "round",
    coreId: "eva-soft",
    faceId: "fiberglass",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 60,
    weightG: 355,
    balanceCm: 25.5,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "mid",
    sourceConfidence: "high",
    sourceCount: 3,
    note: "Lightweight comfort round racket for early-intermediates; brand + padel.fyi + Padel USA confirm round shape, 355g, soft foam core and fiberglass face; exact balance cm derived from head-light rating.",
  },
  {
    id: "head-flash-pro-2023",
    brand: "Head",
    model: "Flash Pro 2023",
    shapeId: "teardrop",
    coreId: "eva-soft",
    faceId: "fiberglass",
    frameId: "carbon-frame",
    surfaceId: "smooth",
    textureLevel: 14,
    weightG: 365,
    balanceCm: 27.0,
    thicknessMm: 38,
    level: "beginner",
    priceTier: "mid",
    sourceConfidence: "high",
    sourceCount: 3,
    note: "Oversized beginner/casual teardrop; Total Padel + Racketguide + Padel USA/brand confirm teardrop shape, 365g, soft Power-Foam EVA core and fiberglass face; balance from Head's published 275mm figure, surface inferred smooth.",
  },
  {
    id: "adidas-adipower-multiweight-3-3-2024",
    brand: "Adidas",
    model: "Adipower Multiweight 3.3 2024",
    shapeId: "diamond",
    coreId: "eva-hard",
    faceId: "carbon-18k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 60,
    weightG: 360,
    balanceCm: 26.5,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    sourceCount: 4,
    note: "Advanced diamond power racket with an adjustable weight/balance system; padel.fyi + All For Padel + Padel USA + Casas Padel confirm diamond shape, ~353-365g, hard EVA core and 18K carbon face; balance cm derived (adjustable, ships head-heavy).",
  },
  {
    id: "adidas-cross-it-2024",
    brand: "Adidas",
    model: "Cross It 2024",
    shapeId: "diamond",
    coreId: "eva-hard",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 70,
    weightG: 368,
    balanceCm: 26.8,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    sourceCount: 4,
    note: "Adidas's attacking diamond with long handle; padel.fyi + PadelNuestro + padelful + Padel USA confirm diamond shape, ~368g, hard EVA core and woven carbon face; face K-count mapped from '15K' to nearest enum, balance derived from measured ~26.9cm.",
  },
  {
    id: "adidas-rx-series-2026",
    brand: "Adidas",
    model: "RX Series 2026",
    shapeId: "round",
    coreId: "eva-soft",
    faceId: "fiberglass",
    frameId: "carbon-frame",
    surfaceId: "smooth",
    textureLevel: 14,
    weightG: 365,
    balanceCm: 25.5,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "mid",
    sourceConfidence: "high",
    sourceCount: 3,
    note: "Comfort/versatile round racket for developing players; All For Padel + Zona de Padel + padelreference confirm round shape, 360-375g, soft EVA core and fiberglass face; balance and surface texture derived.",
  },
  {
    id: "bullpadel-elite-2024",
    brand: "Bullpadel",
    model: "Elite 2024",
    shapeId: "teardrop",
    coreId: "eva-medium",
    faceId: "fiberglass",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 60,
    weightG: 355,
    balanceCm: 25.8,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "premium",
    sourceConfidence: "high",
    sourceCount: 3,
    note: "Gemma Triay's lightweight versatile signature; brand + padel.fyi + racketguide/padelvo agree on teardrop shape, ~350-360g, MultiEVA core and Fibrix face; core mapped to eva-medium, Fibrix mapped to fiberglass, balance cm derived from unanimous even rating.",
  },
  {
    id: "bullpadel-flow-2024",
    brand: "Bullpadel",
    model: "Flow 2024",
    shapeId: "diamond",
    coreId: "eva-medium",
    faceId: "fiberglass",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 65,
    weightG: 355,
    balanceCm: 26.4,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "premium",
    sourceConfidence: "high",
    sourceCount: 3,
    note: "Alejandra Salazar's lightweight diamond; brand + padel.fyi + racketguide/padelful agree on diamond shape, ~350-360g, MultiEVA core and Fibrix rough face; core mapped to eva-medium, Fibrix to fiberglass, balance cm derived from head-heavy rating.",
  },
  {
    id: "bullpadel-ionic-control-2024",
    brand: "Bullpadel",
    model: "Ionic Control 2024",
    shapeId: "round",
    coreId: "eva-medium",
    faceId: "fiberglass",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 55,
    weightG: 370,
    balanceCm: 25.2,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "mid",
    sourceConfidence: "high",
    sourceCount: 3,
    note: "Round control racket from the Ionic line; brand + padel.fyi + padelreference/racketguide agree on round shape, 365-375g, 38mm, MultiEVA core with carbon+fiberglass face; core mapped to eva-medium, face to fiberglass, balance cm derived from head-light rating.",
  },
  {
    id: "babolat-air-viper-2024",
    brand: "Babolat",
    model: "Air Viper 2024",
    shapeId: "teardrop",
    coreId: "eva-medium",
    faceId: "carbon-18k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 75,
    weightG: 355,
    balanceCm: 26.5,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    sourceCount: 3,
    note: "Speed/attack racket; Babolat.com + padel.fyi + padelful/racketguide agree on teardrop shape, 355g, 38mm, X-EVA core and 16K carbon face; core mapped to eva-medium, 16K bucketed to carbon-18k; balance 26.5 is the brand's published 265mm figure.",
  },
  {
    id: "babolat-counter-viper-2024",
    brand: "Babolat",
    model: "Counter Viper 2024",
    shapeId: "round",
    coreId: "eva-medium",
    faceId: "carbon-3k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 72,
    weightG: 365,
    balanceCm: 25.5,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "approximate",
    sourceCount: 3,
    note: "Control-oriented racket; Babolat.com + Fromuth + racketguide/padelful agree on 365g, 38mm, X-EVA core and 3K carbon face; shape marked approximate because 2024 sources call it hybrid vs brand's round, and head-light balance is derived.",
  },
  {
    id: "babolat-contact-2024",
    brand: "Babolat",
    model: "Contact 2024",
    shapeId: "round",
    coreId: "eva-soft",
    faceId: "fiberglass",
    frameId: "carbon-frame",
    surfaceId: "smooth",
    textureLevel: 15,
    weightG: 340,
    balanceCm: 25.2,
    thicknessMm: 38,
    level: "beginner",
    priceTier: "budget",
    sourceConfidence: "high",
    sourceCount: 3,
    note: "Entry-level easy-to-play racket; Babolat.com + Padel USA + padelreference/doittennis agree on round shape, 340g, 38mm, EVA core, fiberglass smooth surface; beginner EVA mapped to eva-soft, balance cm derived from head-light rating.",
  },
  {
    id: "wilson-ultra-pro-v2-2023",
    brand: "Wilson",
    model: "Ultra Pro V2",
    shapeId: "diamond",
    coreId: "eva-hard",
    faceId: "carbon-3k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 62,
    weightG: 356,
    balanceCm: 26.0,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    sourceCount: 3,
    note: "Wilson's top Ultra-line power racket; Wilson.com + Racquet Point + Padelreference confirm diamond shape, 356g, firm EVA core and Double Carbon Wall face; balance 26.0 is the published 260mm figure, K-count mapped to carbon-3k (only generic carbon stated).",
  },
  {
    id: "wilson-ultra-team-v2-2023",
    brand: "Wilson",
    model: "Ultra Team V2",
    shapeId: "diamond",
    coreId: "eva-soft",
    faceId: "fiberglass",
    frameId: "fiberglass-frame",
    surfaceId: "rough",
    textureLevel: 62,
    weightG: 366,
    balanceCm: 26.1,
    thicknessMm: 38,
    level: "beginner",
    priceTier: "budget",
    sourceConfidence: "approximate",
    sourceCount: 3,
    note: "Entry Ultra-line racket; Wilson.com + Racquet Point + Amazon confirm fiberglass face/frame, ~366g, 38mm; marked approximate because retailers market diamond while published balance is an even 26.1cm and core wording varies between Core Foam and EVA.",
  },
  {
    id: "starvie-metheora-2024",
    brand: "StarVie",
    model: "Metheora 2024",
    shapeId: "round",
    coreId: "eva-soft",
    faceId: "carbon-3k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 75,
    weightG: 365,
    balanceCm: 25.5,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    sourceCount: 3,
    note: "Spanish-made round control racket (soft version); Padelful + padel.fyi + Racketguide agree on round shape, ~365g, EVA Soft 30 core and 3K carbon face; balance cm derived (round, head-light), thickness standard 38mm.",
  },
  {
    id: "starvie-basalto-pro-2024",
    brand: "StarVie",
    model: "Basalto Pro 2024",
    shapeId: "teardrop",
    coreId: "eva-hard",
    faceId: "carbon-3k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 60,
    weightG: 368,
    balanceCm: 26.3,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "approximate",
    sourceCount: 3,
    note: "Hard power-oriented teardrop; padel.fyi + Padelful + Padelnuestro agree on teardrop shape, 368g, Hard EVA core and 3K carbon (with basalt layer) face; balance approximate (spec says even but a heavy test unit measured 27.6cm), 26.3 is a mid estimate.",
  },
  {
    id: "siux-trilogy-pro-5-2025",
    brand: "Siux",
    model: "Trilogy Pro 5 2025",
    shapeId: "round",
    coreId: "eva-medium",
    faceId: "carbon-18k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 62,
    weightG: 365,
    balanceCm: 25.1,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    sourceCount: 3,
    note: "Top Trilogy control racket, round + low balance; Padel USA + Padelreference + Padelshop agree on round shape, 355-375g, 24K carbon face (mapped to carbon-18k per rule) and EVA core; balance cm derived from low-balance + round, 38mm standard.",
  },
  {
    id: "siux-trilogy-elite-5-2025",
    brand: "Siux",
    model: "Trilogy Elite 5 2025",
    shapeId: "round",
    coreId: "eva-medium",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 60,
    weightG: 365,
    balanceCm: 25.2,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "mid",
    sourceConfidence: "high",
    sourceCount: 3,
    note: "Round low-balance control/comfort Trilogy; Padelreference + Padel USA + Racketguide agree on round shape, 355-375g, 12K carbon face, EVA core and rough surface; core density generic (eva-medium), balance cm derived from low-balance rating.",
  },
  {
    id: "varlion-maxima-summum-prisma-soft-2024",
    brand: "Varlion",
    model: "Maxima Summum Prisma Soft 2024",
    shapeId: "teardrop",
    coreId: "eva-soft",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 75,
    weightG: 353,
    balanceCm: 25.7,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    sourceCount: 4,
    note: "Pro-line control teardrop from the Maxima series; Varlion + padelreference + padelful + Amazon official spec confirm rounded-teardrop shape, 340-365g, soft Softcolor EVA and 12K carbon face; exact balance cm derived from control/even balance.",
  },
  {
    id: "varlion-lw-carbon-ti-2024",
    brand: "Varlion",
    model: "LW Carbon Ti 2024",
    shapeId: "round",
    coreId: "eva-medium",
    faceId: "carbon-3k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 75,
    weightG: 355,
    balanceCm: 25.2,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "mid",
    sourceConfidence: "approximate",
    sourceCount: 3,
    note: "Round control racket; Varlion + racketcentral + padelpadel/Amazon confirm round shape, 350-360g, medium EVA; face marked approximate (sources conflict carbon vs fiberglass laminate, no weave agreed), balance cm derived from head-light rating.",
  },
  {
    id: "black-crown-special-2024",
    brand: "Black Crown",
    model: "Special 2024",
    shapeId: "teardrop",
    coreId: "eva-medium",
    faceId: "carbon-3k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 62,
    weightG: 362,
    balanceCm: 26.0,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "mid",
    sourceConfidence: "high",
    sourceCount: 3,
    note: "Advanced power teardrop; padel-point + padelmarket + esprit-padel/padelreference confirm teardrop shape, 355-370g, Power Soft Memory EVA and 3K carbon rough face; balance cm derived from published high-balance rating.",
  },
  {
    id: "dunlop-galactica-pro-2025",
    brand: "Dunlop",
    model: "Galactica Pro 2025",
    shapeId: "teardrop",
    coreId: "eva-medium",
    faceId: "carbon-18k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 70,
    weightG: 368,
    balanceCm: 25.8,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    sourceCount: 4,
    note: "Advanced control/power teardrop; padelful + zonadepadel + padelscout + Dunlop US confirm teardrop shape, 360-375g, Pro EVA core and 16K carbon face (bucketed to carbon-18k); balance cm derived from medium balance.",
  },
  {
    id: "dunlop-boost-control-2-0-2024",
    brand: "Dunlop",
    model: "Boost Control 2.0 2024",
    shapeId: "round",
    coreId: "eva-soft",
    faceId: "fiberglass",
    frameId: "carbon-frame",
    surfaceId: "smooth",
    textureLevel: 14,
    weightG: 355,
    balanceCm: 25.4,
    thicknessMm: 38,
    level: "beginner",
    priceTier: "budget",
    sourceConfidence: "approximate",
    sourceCount: 3,
    note: "Beginner/game-improver round; padelnuestro + racketguide + smashinn/squashgearpro confirm round shape, 355g, medium balance and soft EVA; face marked approximate (sources give carbon+fiberglass only at line level, fiberglass inferred for entry model), balance cm derived.",
  },
  {
    id: "drop-shot-conqueror-attack-2-0-2026",
    brand: "Drop Shot",
    model: "Conqueror Attack 2.0 2026",
    shapeId: "diamond",
    coreId: "eva-hard",
    faceId: "carbon-18k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 70,
    weightG: 368,
    balanceCm: 26.4,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    sourceCount: 4,
    note: "Advanced power diamond; zonadepadel + padelful + padelreference + padelproshop confirm diamond shape, 360-375g, EVA Pro High Density core and 24K carbon face (mapped to carbon-18k) with spin texture; balance cm derived from medium-high rating.",
  },
  {
    id: "vibor-a-black-mamba-pro-2-0-2026",
    brand: "Vibor-A",
    model: "Black Mamba PRO 2.0 2026",
    shapeId: "teardrop",
    coreId: "eva-medium",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 65,
    weightG: 367,
    balanceCm: 26.0,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "high",
    sourceCount: 4,
    note: "Advanced attack-leaning teardrop; padelscout + zonadepadel + padelproshop/mprosports + brand confirm teardrop shape, 360-375g, 12K carbon face, EVA Pro core and textured surface; balance cm derived from medium-high rating, core mapped from firm/medium hardness.",
  },
  {
    id: "kuikma-pr990-hybrid-soft-2022",
    brand: "Kuikma",
    model: "PR990 Hybrid Soft",
    shapeId: "teardrop",
    coreId: "eva-soft",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "smooth",
    textureLevel: 50,
    weightG: 367,
    balanceCm: 25.7,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "budget",
    sourceConfidence: "high",
    sourceCount: 3,
    note: "Intermediate control/hybrid teardrop; padel.fyi + padelful + Decathlon/Kuikma confirm teardrop shape, ~362-372g, soft EVA core and 12K carbon face; balance cm derived from even rating, thickness and smooth surface derived (standard for line).",
  },
  {
    id: "kombat-black-18k-2023",
    brand: "Kombat",
    model: "Black 18K 2023",
    shapeId: "diamond",
    coreId: "eva-medium",
    faceId: "carbon-18k",
    frameId: "carbon-frame",
    surfaceId: "rough",
    textureLevel: 62,
    weightG: 365,
    balanceCm: 26.4,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "mid",
    sourceConfidence: "high",
    sourceCount: 3,
    note: "Advanced power diamond; padelful + Kombat brand + gearvolley confirm diamond shape, 350-380g, rough 18K carbon face, high-recovery Black EVA and 100% carbon frame; balance cm derived from diamond/head-heavy, thickness derived (standard).",
  },
  {
    id: "vairo-compact-signature-2023",
    brand: "Vairo",
    model: "Compact Signature 2023",
    shapeId: "round",
    coreId: "eva-hard",
    faceId: "carbon-12k",
    frameId: "carbon-frame",
    surfaceId: "smooth",
    textureLevel: 14,
    weightG: 370,
    balanceCm: 25.2,
    thicknessMm: 38,
    level: "advanced",
    priceTier: "premium",
    sourceConfidence: "approximate",
    sourceCount: 3,
    note: "Advanced round control racket; zonadepadel + PadelNuestro + originalpadel/time2padel agree on round shape, 365-375g, 12K carbon face, carbon frame, smooth finish; marked approximate because core hardness conflicts (hard vs medium), balance cm derived from round shape.",
  },
  {
    id: "enebe-aerox-7-2-carbon-reloaded-2024",
    brand: "Enebe",
    model: "Aerox 7.2 Carbon Reloaded 2024",
    shapeId: "teardrop",
    coreId: "eva-medium",
    faceId: "carbon-3k",
    frameId: "carbon-frame",
    surfaceId: "smooth",
    textureLevel: 14,
    weightG: 363,
    balanceCm: 25.8,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "mid",
    sourceConfidence: "high",
    sourceCount: 4,
    note: "Intermediate versatile teardrop; Enebe brand + zonadepadel + padelful + tiendapadelpoint confirm teardrop shape, 355-370g, 3K carbon face, Black EVA HR3 medium core and 38mm; balance cm derived from medium, surface smooth derived from glossy finish.",
  },
  {
    id: "mystica-legacy-hybrid-2024",
    brand: "Mystica",
    model: "Legacy Hybrid 2024",
    shapeId: "teardrop",
    coreId: "eva-soft",
    faceId: "fiberglass",
    frameId: "fiberglass-frame",
    surfaceId: "smooth",
    textureLevel: 14,
    weightG: 365,
    balanceCm: 25.7,
    thicknessMm: 38,
    level: "intermediate",
    priceTier: "budget",
    sourceConfidence: "approximate",
    sourceCount: 4,
    note: "Beginner-friendly hybrid teardrop; time2padel + padeliberico + ofertasdepadel + palafinder agree on hybrid/teardrop shape, 355-375g, EVA core and fiberglass faces; marked approximate (retailer-only coverage, no direct brand spec), core density, surface, balance and thickness derived.",
  },
];
const CORS = { "content-type": "application/json", "cache-control": "public, max-age=300, s-maxage=3600", "access-control-allow-origin": "*", "access-control-allow-methods": "GET, OPTIONS", "access-control-allow-headers": "content-type" };

export default async function handler(req) {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: CORS });
  if (req.method !== "GET") return new Response(JSON.stringify({ error: "GET only" }), { status: 405, headers: CORS });
  const slim = MARKET_RACQUETS.map((r) => ({
    id: r.id, brand: r.brand, model: r.model, level: r.level, priceTier: r.priceTier, note: r.note, shapeId: r.shapeId,
    spec: { shapeId: r.shapeId, coreId: r.coreId, faceId: r.faceId, frameId: r.frameId, surfaceId: r.surfaceId, weightG: r.weightG, balanceCm: r.balanceCm, thicknessMm: r.thicknessMm }
  }));
  return new Response(JSON.stringify({ count: slim.length, racquets: slim }), { status: 200, headers: CORS });
}
